# Generated by Django 4.2.30 on 2026-04-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_booking_comment_remove_booking_guest_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('reservation_date', 'reservation_slot')},
        ),
    ]
